# Generated by Django 2.1.3 on 2018-11-20 01:45

from django.conf import settings
import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SendingSite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street_address', models.CharField(max_length=256)),
                ('multiple_adjacent_sites', models.BooleanField()),
                ('site_size', models.FloatField()),
                ('location', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('fuzzy_location', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('transfer_purpose', models.CharField(max_length=256)),
                ('base_zone', models.CharField(max_length=256)),
                ('base_zone_class', models.CharField(max_length=256)),
                ('plan_district', models.CharField(max_length=256)),
                ('conservation_district', models.CharField(max_length=256)),
                ('historic_district', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sending_sites', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
