# Generated by Django 2.1.3 on 2018-11-28 03:48

from django.conf import settings
import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Auction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reserve_price_sqft', models.IntegerField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='BaseZone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='BaseZoneClass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.IntegerField(choices=[(0, 'Historic'), (1, 'Conservation'), (2, 'Plan')])),
                ('name', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='ReceivingSite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street_address', models.CharField(max_length=256)),
                ('site_size', models.FloatField()),
                ('location', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('fuzzy_location', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('target_far', models.FloatField()),
                ('base_zone_classes', models.ManyToManyField(blank=True, to='sites.BaseZoneClass')),
                ('base_zones', models.ManyToManyField(blank=True, to='sites.BaseZone')),
                ('districts', models.ManyToManyField(blank=True, to='sites.District')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receiving_sites', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SendingSite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street_address', models.CharField(max_length=256)),
                ('site_size', models.FloatField()),
                ('location', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('fuzzy_location', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('transfer_purpose', models.IntegerField(choices=[(0, 'Tree'), (1, 'Affordable Housing'), (2, 'Historic Landmark')])),
                ('transferrable_far', models.FloatField()),
                ('base_zone_classes', models.ManyToManyField(blank=True, to='sites.BaseZoneClass')),
                ('base_zones', models.ManyToManyField(blank=True, to='sites.BaseZone')),
                ('districts', models.ManyToManyField(blank=True, to='sites.District')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sending_sites', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='auction',
            name='receiving_site',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='sites.ReceivingSite'),
        ),
        migrations.AddField(
            model_name='auction',
            name='sending_site',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='sites.SendingSite'),
        ),
        migrations.AddField(
            model_name='auction',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auction', to=settings.AUTH_USER_MODEL),
        ),
    ]
