# Generated by Django 2.1.3 on 2018-11-28 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basezone',
            name='name',
            field=models.IntegerField(choices=[(0, 'CE'), (1, 'CM1'), (2, 'CM2'), (3, 'CM3'), (4, 'CR'), (5, 'CX'), (6, 'R1'), (7, 'R2'), (8, 'R3'), (9, 'RH'), (10, 'RMP'), (11, 'RX'), (12, 'RM1'), (13, 'RM2'), (14, 'RM3'), (15, 'RM4')]),
        ),
        migrations.AlterField(
            model_name='basezoneclass',
            name='name',
            field=models.IntegerField(choices=[(0, 'MDZ'), (1, 'MUZ')]),
        ),
    ]
