# Generated by Django 2.1.3 on 2018-11-28 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0002_auto_20181128_0428'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basezone',
            name='name',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='basezoneclass',
            name='name',
            field=models.CharField(max_length=256),
        ),
    ]
