# Generated by Django 2.1.3 on 2018-11-28 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0003_auto_20181128_0431'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basezone',
            name='name',
            field=models.CharField(max_length=256, unique=True),
        ),
        migrations.AlterField(
            model_name='basezoneclass',
            name='name',
            field=models.CharField(max_length=256, unique=True),
        ),
        migrations.AlterField(
            model_name='district',
            name='name',
            field=models.CharField(max_length=256, unique=True),
        ),
    ]
