# Generated by Django 2.1.3 on 2018-12-01 19:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sites', '0007_auto_20181201_1642'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReceivingSiteDoc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_purpose', models.IntegerField(choices=[(0, 'City Forester or arborist certification'), (1, 'PHB certification'), (2, 'Other certification'), (3, 'Other supporting document')])),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supporting_docs', to='sites.ReceivingSite')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receivingsitedoc_supporting_docs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SendingSiteDoc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_purpose', models.IntegerField(choices=[(0, 'City Forester or arborist certification'), (1, 'PHB certification'), (2, 'Other certification'), (3, 'Other supporting document')])),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supporting_docs', to='sites.SendingSite')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sendingsitedoc_supporting_docs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
