# Generated by Django 2.1.3 on 2018-12-04 04:08

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sites', '0008_receivingsitedoc_sendingsitedoc'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bid',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField()),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='auction',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2018, 12, 4, 4, 8, 6, 171524, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='auction',
            name='end',
            field=models.DateTimeField(default=datetime.datetime(2018, 12, 4, 4, 8, 14, 587331, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='auction',
            name='start',
            field=models.DateTimeField(default=datetime.datetime(2018, 12, 4, 4, 8, 21, 236887, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='auction',
            name='starting_price_sqft',
            field=models.FloatField(default=1.0),
        ),
        migrations.AlterField(
            model_name='auction',
            name='reserve_price_sqft',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='auction',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auctions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='bid',
            name='auction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bids', to='sites.Auction'),
        ),
        migrations.AddField(
            model_name='bid',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bids', to=settings.AUTH_USER_MODEL),
        ),
    ]
