# Generated by Django 2.1.3 on 2018-12-04 05:28

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0009_auto_20181204_0408'),
    ]

    operations = [
        migrations.AddField(
            model_name='receivingsite',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2018, 12, 4, 5, 28, 10, 27134, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sendingsite',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2018, 12, 4, 5, 28, 16, 706884, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
