# Generated by Django 2.1.3 on 2018-12-08 03:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0011_remove_auction_receiving_site'),
    ]

    operations = [
        migrations.AddField(
            model_name='bid',
            name='receiving_site',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='sites.ReceivingSite'),
        ),
    ]
