# Generated by Django 2.1.3 on 2018-12-08 03:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0012_bid_receiving_site'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bid',
            name='receiving_site',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='bids', to='sites.ReceivingSite'),
        ),
    ]
