# Generated by Django 2.1.3 on 2018-12-09 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0013_auto_20181208_0322'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sendingsite',
            name='transfer_purpose',
            field=models.IntegerField(choices=[(0, 'Tree'), (1, 'Affordable Housing'), (2, 'Historic Landmark'), (3, 'Other')]),
        ),
        migrations.AlterField(
            model_name='sendingsite',
            name='transferrable_far',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
